//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 MCAD.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDD_DLGPROPTEXT                 103
#define IDR_MAINFRAME                   128
#define IDR_MMTYPE                      129
#define IDR_TB_PAGE                     130
#define IDR_TB_LINE                     131
#define IDR_FON_HZ                      140
#define IDR_FON_EN                      141
#define IDR_MENU_LIST                   150
#define IDR_MENU_PIECE                  151
#define IDR_MENU_LINE                   152
#define IDB_START                       160
#define IDDLG_GET_INPUT                 201
#define IDDLG_PARA_MAC                  202
#define IDDLG_PARA_PROTECT              203
#define IDD_ABOUTBOX2                   203
#define IDDLG_PARA_SOFT                 204
#define IDDLG_PROP_DRILLTABLE           205
#define IDDLG_PROP_LINE_ADD             206
#define IDDLG_PROP_LINE_INFLATE         207
#define IDDLG_PROP_MEANDERLINE          208
#define IDDLG_PROP_OUTLINE1             209
#define IDDLG_PROP_SLOT                 210
#define IDDLG_PWD                       211
#define IDDLG_REG                       212
#define IDDLG_SUPER_USER                213
#define IDDLG_TEST                      214
#define IDDLG_PROP_RECT                 215
#define IDDLG_PROP_TEXT_ADD             216
#define IDD_ABOUT_GM                    217
#define IDD_ABOUT_ALL                   217
#define IDCHK_LT                        1000
#define IDCHK_LB                        1001
#define IDCHK_RT                        1002
#define IDCHK_RB                        1003
#define IDCHK_CLOCKWISE                 1004
#define IDTCHK_PD                       1005
#define IDTCHK_CD                       1006
#define IDTCHK_MD                       1007
#define IDTCHK_VMON                     1008
#define IDTCHK_MMON                     1009
#define IDCHK_VMEN                      1010
#define IDTB_PAGE1                      1011
#define IDTB_PAGE2                      1012
#define IDTB_PAGE3                      1013
#define IDTB_PAGE4                      1014
#define IDTB_PAGE5                      1015
#define IDTBTN_TO_DEFZP                 1020
#define IDBTN_PROCPARA                  1021
#define IDBTN_PARA_SAVE                 1022
#define IDBTN_PARA_RESTORE              1023
#define TDTB_ZOOMIN                     1024
#define TDTB_ZOOMOUT                    1025
#define TDTB_ZOOMALL                    1026
#define IDTB_MAN_CTRL                   1027
#define IDTB_MAC_PARA                   1028
#define IDCB_START                      1029
#define IDCB_PAUSE                      1030
#define IDCB_CANCEL                     1031
#define IDTBS_DRAW_LINE                 1040
#define IDTBS_DRAW_CURVE                1041
#define IDTBS_DRAW_RECT                 1042
#define IDTBS_ADRILL                    1043
#define IDTBS_SCURVE                    1044
#define IDTBS_SPIECE                    1045
#define IDTBS_CUT_SEQ                   1046
#define IDTBS_ADD_TEXT                  1047
#define IDCB_SEL_ALL                    1048
#define IDCB_DEMO_START                 1049
#define IDCE_RECT_SIZE_X                1060
#define IDCE_RECT_SIZE_Y                1061
#define IDCE_WORK_STARTX                1062
#define IDCE_WORK_STARTY                1063
#define ID_HyperLinkWebSite             1064
#define IDCOMBO_CUT_POS                 1068
#define IDCE_CUT_WIDTH                  1069
#define IDCE_CUT_DIST                   1070
#define IDCE_CUT_DEPTH                  1071
#define IDTBTN_SAVEPP                   1073
#define IDTBTN_SAVECP                   1074
#define IDTBTN_SAVE_WM                  1076
#define IDTBTN_OK                       1077
#define IDCE_TEXT_X                     1078
#define IDCE_TEXT_Y                     1079
#define IDCE_TEXT_ANGLE                 1080
#define IDCE_TEXT_Y3                    1081
#define IDCE_TEXT_CONTENT               1081
#define IDC_SLIDER1                     1082
#define IDCE_TEXT_INFLATE               1083
#define IDTCE_PWM_PLOT                  1100
#define IDTCE_PWM_CUT                   1101
#define IDTCE_Z_POS                     1102
#define IDCE_LINE_LEN                   1103
#define IDCE_LINE_ANGLE                 1104
#define IDCE_PLATFORM_XSIZE             1105
#define IDCE_PLATFORM_YSIZE             1106
#define IDCE_GAP_X                      1107
#define IDCE_MMDIR                      1108
#define IDCE_DOTNUM_X                   1109
#define IDCE_DOTNUM_Y                   1110
#define IDCE_GAP_Y                      1111
#define IDCE_START_Y                    1112
#define IDCE_START_X                    1113
#define IDCE_POS_MOVE                   1114
#define IDCE_TOP                        1115
#define IDCE_LEFT                       1116
#define IDCE_RIGHT                      1117
#define IDCE_BOTTOM                     1118
#define IDCE_RADIUS                     1119
#define IDCE_D_INPUT                    1120
#define IDCE_SLOT_WIDTH                 1121
#define IDCE_END_DATE                   1122
#define IDCE_PWD                        1123
#define IDCE_PASSWORD                   1124
#define IDCE_SN                         1125
#define IDCE_CODE                       1126
#define IDCE_RANDPW                     1127
#define IDCE_ZOOM_LEVEL                 1128
#define IDCE_SIZEX                      1129
#define IDCE_SIZEY                      1130
#define IDCE_DIRLL_DIMENSION            1131
#define IDCE_BEFORE                     1132
#define IDCE_AFTER                      1133
#define IDCE_EXPORT_PENNUM              1134
#define IDCE_EXPORT_CUTNUM              1135
#define IDCE_EXPORT_DRILLNUM            1136
#define IDCE_SPD_PLOT                   1137
#define IDCE_SPD_CUT                    1138
#define IDCE_SPD_MILLING                1139
#define IDCE_SPD_MOVE                   1140
#define IDCE_PWM_PLOT                   1141
#define IDCE_PWM_CUT                    1142
#define IDCE_POS_WORK                   1143
#define IDCE_MPDIST_X                   1144
#define IDCE_MPDIST_Y                   1145
#define IDCE_KPDIST_X                   1146
#define IDCE_KPDIST_Y                   1147
#define IDCE_10000X                     1148
#define IDCE_10000Y                     1149
#define IDCE_ANGLE_ADJ                  1150
#define IDCE_MMOTOR_DELAY               1151
#define IDCE_MAXPP_X                    1152
#define IDCE_MAXPP_Y                    1153
#define IDCE_PPMMX                      1154
#define IDCE_PPMMY                      1155
#define IDCE_PPMMZ                      1156
#define IDC_TXT1                        1200
#define IDC_TXT2                        1201
#define IDC_TXT3                        1202
#define IDC_TXT_PW                      1203
#define IDTXT_INPUT                     1204
#define IDTXT_PWD                       1205
#define IDTXT_RAND_CODE                 1206
#define IDCB_INPUT_REGCODE              1207
#define IDC_URL                         1208
#define IDM_PLT_IMPORT                  32001
#define IDM_AUTH_UPDATE                 32002
#define IDM_SUPER_USER                  32003
#define IDM_APP_MANUAL                  32004
#define IDM_LIST_CLEAR                  32005
#define IDM_PARA_SOFT                   32006
#define IDM_APP_VIDEO                   32007
#define IDMP_MAKEACOPY                  32010
#define IDMP_MIRROR                     32011
#define IDMP_ADDOUTLINE1                32012
#define IDMP_ADDOUTLINE2                32013
#define IDMP_COMBINE                    32014
#define IDMP_90CCW                      32015
#define IDMP_90CW                       32016
#define IDMP_01CCW                      32017
#define IDMP_01CW                       32018
#define IDMP_SEL_TOLIST                 32019
#define IDMP_REMOVE_ALL                 32020
#define IDMP_REMOVE                     32021
#define IDMP_ALL_TOLIST                 32022
#define IDMP_COPY_MIRROR                32023
#define IDML_TO_PEN                     32030
#define IDML_TO_MM                      32031
#define IDML_CURVE_TO_SLOT              32032
#define IDML_CURVE_MERGE                32033
#define IDML_CURVE_REVERSE              32034
#define IDML_BK_BY_ANGLE                32035
#define IDML_POLY_INFLATE               32036
#define IDML_POLY_SHRINK                32037
#define IDML_CURVE_REMOVE               32038
#define IDML_CURVE_EXPAND               32039
#define IDML_FORCE_TO_POLY              32040
#define IDML_FIND_OUTLINE               32041
#define IDML_LINE_TO_DOT                32042
#define IDML_SET_CURVE_START            32043
#define IDS_PT_MM                       32100
#define IDS_SYS_STATE                   32101
#define IDS_PROGRESS                    32102
#define IDM_MAN_CTRL                    32103
#define ID_FILE_EXPORT_PLT              32110
#define ID_FILE_ADD_SNAKE_LINE          32111
#define ID_FILE_ADD_DRILL_TABLE         32112
#define ID_FILE_ADD_MP_TEST             32113

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        163
#define _APS_NEXT_COMMAND_VALUE         32873
#define _APS_NEXT_CONTROL_VALUE         1084
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
